betterScrabble/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from . import views
from  django.urls import path
app_name = 'main'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path("contact/",views.contact,name = 'contact'),
    path("creator/", views.gameroom_creator, name='creator'),
    path("game/<str:gameroom_id>/", views.game, name='game'),
    path("gameroom/", views.gameroom, name='gameroom'),
    path("login/", views.login_request, name='login'),
    path("logout/", views.logout_request, name='logout'),
    path("profile/<user_id>/", views.profile, name='profile'),
    path("register/", views.register, name='register')
]

main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    # def save(self, *args, **kwargs):
    #     super(Profile, self).save(*args, **kwargs)
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)


class GameRooms(models.Model):
    name = models.CharField(max_length=250, default="Too lazy to name")
    in_progress = models.BooleanField(default=False)
    board_state = models.TextField( default=",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,,")
    seats = models.PositiveIntegerField(default=2)
    finished = models.BooleanField(default=False)
class Game(models.Model):
    game_room = models.ForeignKey(GameRooms, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    points = models.IntegerField(default=0)

class Move(models.Model):
    game_room = models.ForeignKey(GameRooms, on_delete=models.CASCADE)
    player = models.CharField(max_length= 500, default=None)
    board_state = models.TextField( default=",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,," \
                                                           ",,,,,,,,,,,,,,,")
    points = models.IntegerField(default=0)
    round = models.IntegerField(default=0)
    # points trzeba liczyć po stronie usera, bo on ma te pdwójne, potrójne pola i najwyżej zerować jak nie ma w słowniku i tyle

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import GameRooms


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user


class GameRoomCreatorForm(forms.ModelForm):
	class Meta:
		model = GameRooms
		fields = ['name', 'seats']

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import GameRooms, Game
from .forms import *
import json

lastBoardState = [  ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,," \
                    ",,,,,,,,,,,,,,,"]


def contact(request):
    return render(request, "main/contact.html")


def homepage(request):
    return render(request, "main/home.html")


@login_required
def game(request, gameroom_id):
    game_room = GameRooms.objects.get(pk=gameroom_id)
    if len(Game.objects.filter(game_room=game_room)) == game_room.seats:
        board_state = game_room.board_state
        print(board_state)
        return render(request, "main/viewgame.html", {"boardState" : board_state,
                                                     'gameroom_id_json': mark_safe(json.dumps(gameroom_id))})
    else:
        return render(request, "main/game.html", {"boardState": lastBoardState[0],
                                              'gameroom_id_json': mark_safe(json.dumps(gameroom_id))})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Zalogowano jako: {username}")
                return redirect("main:homepage")
            else:
                messages.error(request, "Błędna nazwa użytkownika lub hasło")
        else:
            messages.error(request, "Błędna nazwa użytkownika lub hasło")
    form = AuthenticationForm()
    return render(request, "main/login.html", {"form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Pomyślnie wylogowano")
    return redirect("main:homepage")


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,
                             f"Zarejestrowano pomyślnie")
            login(request, user)
            messages.info(request, f"Zalogowano jako: {username}")
            return redirect("main:homepage")
        else:
            for msg in form.errors:
                for x in form.errors[msg]:
                    messages.error(request, f" {x} ")

    form = NewUserForm
    return render(request, "main/register.html", context={"form": form})


@login_required
def gameroom(request):
    return render(request,"main/gameroom.html",context = {"gamerooms": GameRooms.objects.all().order_by('pk')})


@login_required
def gameroom_creator(request):
    if request.method == "POST":
        form = GameRoomCreatorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,
                             f"Utworzono grę!")
        else:
            print("Błąd")
        return redirect("main:gameroom")
    else:
        form = GameRoomCreatorForm()
    return render(request, "main/gameroom_creator.html", context={"form": form})


@login_required
def profile(request,user_id):
    user = User.objects.get(pk=user_id)
    played_games = Game.objects.filter(user=user).select_related('game_room')
    return render(request, "main/profile.html", context={'playedGames': played_games})

templates/main/contact.html
{% extends "main/header.html" %}
{% block content %}
    <span>

  <ul class="collection">
    <li class="collection-item avatar">
      <img src="https://media-exp1.licdn.com/dms/image/C4D03AQFg9yechKvwJA/profile-displayphoto-shrink_200_200/0?e=1585180800&v=beta&t=OXB06RO6kJt2aKqk7BfQvOd3hxNWzOK9-8mUAsK-rSU" alt="" class="circle">
      <span class="title"> Łukasz </span>
      <p>Dawydzik </p>
    </li>
    <li class="collection-item avatar">
      <i class="material-icons circle">mail</i>
      <span class="title">Mail</span>
      <p> l.dawydzik@gmail.com </p>
    </li>
    <li class="collection-item avatar">
      <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="" class="circle">
      <span class="title">Github</span>
        <p><a href="https://github.com/wydzik" target="_blank"> Mój profil Github </a></p>
    </li>
    <li class="collection-item avatar">
      <img src="https://content.linkedin.com/content/dam/me/business/en-us/amp/brand-site/v2/bg/LI-Bug.svg.original.svg" alt="" class="circle" >
      <span class="title">Linkedin</span>
        <p><a href="https://www.linkedin.com/in/%C5%82ukasz-dawydzik/" target="_blank"> Mój profil Linkedin</a></p>
    </li>
  </ul>
    </span>
{% endblock %}

templates/main/gameroom.html
{% extends "main/header.html" %}
{% block content %}
<main role="main" class="grid-container">
    <div>
        <table>
            <tr id="header">
                <td>ID Gry</td>
                <td>Nazwa gry</td>
                <td>W Trakcie</td>
                <td>Miejsc przy stole</td>
                <td>Zakończona</td>
            </tr>
            {% for gameroom in gamerooms %}
            <tr>
                <td>{{ gameroom.id }}</td>
                <td><a href="{% url 'main:game' gameroom.id %}">{{ gameroom.name }}</a></td>
                {% if gameroom.in_progress %}
                <td>TAK</td>
                {% elif not gameroom.in_progress %}
                <td>NIE</td>
                {% endif %}
                <td>{{ gameroom.seats }}</td>
            {% if gameroom.finished %}
                <td>TAK</td>
                {% elif not gameroom.finished %}
                <td>NIE</td>
                {% endif %}
            </tr>
{% endfor %}
            <tr>
                <td><a href="{% url 'main:creator' %}">Utwórz nową grę</a></td>
            </tr>
        </table>
    </div>

</div>
</main>
{% endblock %}

templates/main/gameroom_creator.html
{% extends "main/header.html" %}
{% block content %}

<h2>Stwórz nową grę!</h2>
<form method="post">
        {% csrf_token %}
    {{ form.as_p }}
    <button class="btn" type="submit" >Graj! </button>
</form>

{% endblock %}

templates/main/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->

 <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>



    {% if title %}
        <title>SCRBL - {{ title }}</title>
    {% else %}
        <title>SCRBL</title>
{% endif %}
</head>
<body>

  {% include "main/navbar.html" %}
  {% include "main/toast.html" %}
 <main role="main" class="container">
          {% block content %}{% endblock %}
 </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</body>
<style>

</style>
</html>

templates/main/home.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Homepage</title>#}
{#</head>#}
{#<body>#}
{#    <div id = "header"></div>#}
{#        <h1>Better Scrabble</h1>#}
{#        <ul>#}
{#            <li><a href="#home">Home</a></li>#}
{#            <li><a href="#login">Login</a></li>#}
{#            <li><a href="#leaderboard">Leaderboard</a></li>#}
{#            <li><a href="#game">Game</a></li>#}
{#        </ul>#}
{#    </div>#}
{#</body>#}
{#</html>#}

{% extends "main/header.html" %}
{% block content %}
 <ul class="collapsible">
    <li class = "active">
      <div class="collapsible-header"><i class=" material-icons">apps </i> O aplikacji</div>
      <div class="collapsible-body">
          <span>Aplikacja wykonana w ramach pracy inżynierskiej przez Łukasza Dawydzika,<br>
          pod nadzorem Doktor Anny Grocholewskiej-Czuryło, na Politechnice Poznańskiej,<br>
              w roku akademickim 2019/2020. Tematem pracy była Implementacja gry typu scrabble<br>
              – propozycja zmodyfikowanego systemu rozgrywki. Zakres zadań stanowiło: <br>
              1.	Implementacja aplikacji webowej umożliwiającej rozgrywkę w grę typu Scrabble.<br>
              2.	Implementacja zmodyfikowanego systemu rozgrywki.<br>
              3.	Implementacja systemu wieloosobowego.
</span></div>
    </li>
    <li>
        <div class="collapsible-header"><i class="material-icons">apps</i>Zasady</div>
      <div class="collapsible-body">
          <span>
              1. Ady dołączyć do gry, należy wcisnąć START.<br>
              2. Gra rozpocznie się, gdy start wciśnie tylu graczy, dla ilu przewidziana jest rozgrywka.<br>
              3. Nie wolno wychodzić z gry, wyjście skutkuje zakończeniem rozgrywki.<br>
              4. Każdy gracz dostaje ten sam zestaw liter i układa swoje litery w tym samym czasie.<br>
              5. Po ułożeniu liter, należy wcisnąć WYKONAJ. <br>
              6. Jeżeli słowo nie znajduje się w słowniku, za ruch zostanie przyznane 0 punktów. <br>
              7. Po ułożeniu słów przez wszystkich graczy wygrywa ten, który ułożył najlepiej punktowane słowo.<br>
              8. Jeżeli więcej graczy ułoży tak samo punktowane słowo, liczy się czas wykonania ruchu. <br>
              9. Po każdej kolejce, wszyscy gracze otrzymują litery, gracza wygranego, a wygrane słowo pojawi się na planszy.<br>
              10. Jeżeli żaden z graczy nie ułoży poprawnego słowa, następuje koniec gry.<br>
              11. Wygrywa gracz z najwyższą liczbą punktów.<br>
          </span></div>
    </li>
 <li>
        <div class="collapsible-header"><i class="material-icons">apps</i>FAQ</div>
      <div class="collapsible-body">
          <span>
              Q: Czy można tworzyć własne pokoje gry?<br>
              A: Aby utworzyć własny pokój gry, wystarczy wejść w zakładkę "Gra" a następnie wybrać opcję na samym dole "Utwórz nową grę".<br>
              <br>
              Q: Czy mogę dwa razy rozegrać grę w tym samym pokoju?<br>
              A: Nie, każdą grę można rozegrać tylko raz, potem jest dostępny do wglądu końcowy stan gry.<br>
              <br>
              Q: Czy mogę sprawdzić swoje wyniki z poprzednich gier?<br>
              A: Tak, wystarczy wybrać z paska nawigacji pole z nazwą użytkownika.<br>
              <br>
              Q: Czy aplikacja działa na urządzenia mobilne?<br>
              A: Nie, aplikacja jest wyłącznie na komputery. Póki co ;)<br>

          </span></div>
    </li>
  </ul>
<script>
 M.AutoInit();
</script>

{% endblock %}

templates/main/login.html
{% extends "main/header.html" %}

{% block content %}
	<form method="POST">
		<input type="hidden" name="csrfmiddlewaretoken" value="z4MyFbTXMxgfoDVt8Ml1TyKf3QsDIeDpdQo87ElzLa6oUyDWhsU8ogdVtJwlryMk">
		<p><label for="id_username">Nazwa użytkownika:</label>
            <input type="text" name="username" autofocus required id="id_username">
        </p>
        <p><label for="id_password">Hasło:</label>
            <input type="password" name="password" required id="id_password">
        </p>
{% csrf_token %}
		<button class="btn" type="submit">Zaloguj</button>
	</form>

	Nie masz jeszcze konta? <a href='/register'><strong>Zarejestruj się! </strong></a>
    <p></p><a href='/admin'><strong>Logowanie dla administratora </strong></a>

{% endblock %}

templates/main/navbar.html
<nav>
    <div class="nav-wrapper">
    <div class="links">
       <a href="/" class="brand-logo" style = "margin-left: 20px">SCRBL</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
	      <li><a href="/">Strona główna</a></li>
            <li><a href="/gameroom">Gra</a></li>
	        <li><a href="{% url 'main:profile' user.pk %}">{{user.username}}</a></li>
	        <li><a href="/logout">Wyloguj</a></li>
        {% else %}
	      <li><a href="/">Strona główna</a></li>
	        <li><a href="/register">Rejestracja</a></li>
	        <li><a href="/login">Logowanie</a></li>
        {% endif %}
          <li><a href="/contact">Kontakt</a></li>
      </ul>
    </div>
    </div>
    <style>
nav{
     background: olivedrab;
}
    /* visited link */
    .links
    a:visited {
      color: white;
    }

    /* mouse over link */
    a:hover {
      color: white;
    }

    /* selected link */
    a:active {
      color: white;

  }
    a:link{
      text-decoration: none;
    }
  </style>
  </nav>

templates/main/profile.html
{% extends "main/header.html" %}
{% block content %}
<main role="main" class="grid-container">
    <div>
        <table>
            <tr id="header">
                <td>ID Gry</td>
                <td>Nazwa gry</td>
                <td>Punkty zdobyte</td>
            </tr>
            {% for game in playedGames %}
            <tr>
                <td>{{ game.game_room.id }}</td>
                <td><a href="{% url 'main:game' game.game_room.id %}">{{ game.game_room.name }}</a></td>
                <td>{{ game.points }}</td>
            </tr>
{% endfor %}
            <tr>
                <td><a href="{% url 'main:creator' %}">Utwórz nową grę</a></td>
            </tr>
        </table>
    </div>

</div>
</main>
{% endblock %}

templates/main/register.html
{% extends "main/header.html" %}

{% block content %}
	<form method="POST">

		<input type="hidden" name="csrfmiddlewaretoken" value="FreaprDQlj6ymgxl37aIpi5JZIhv2Rg1jdQKRU5skWWHSbfOcNJPU0yppBldLbpW">
		<p><label for="id_username">Nazwa użytkownika:</label>
            <input type="text" name="username" maxlength="150" autofocus required id="id_username">
        </p>
        <p><label for="id_email">Email:</label>
            <input type="email" name="email" required id="id_email">
        </p>
        <p><label for="id_password1">Hasło:</label>
            <input type="password" name="password1" required id="id_password1">
            <span class="helptext"><ul>
                <li>Hasło nie może przypominać nicku ani maila.</li>
                <li>Hasło musi zawierać minimum 8 znaków.</li>
                <li>Hasło musi zawierać minimum 1 Dużą i małą literę.</li>
                <li>Hasło nie może być powszechnie używanym słowem</li></ul>
            </span>
        </p>
        <p><label for="id_password2">Powtórz hasło:</label>
            <input type="password" name="password2" required id="id_password2">
        </p>
            {% csrf_token %}    
		<button class="btn" type="submit">Zarejestruj</button>
	</form>
	Masz już konto? <a href='/login'><strong>Zaloguj się! </strong></a>
{% endblock %}

templates/main/toast.html
{% if messages %}
    {%  for message in messages %}
    <script> M.toast({html: "{{ message }}"});</script>
    {% endfor %}
{% endif %}